sequenceDiagram
    participant browser
    participant server

    browser->>server: https://studies.cs.helsinki.fi/exampleapp/spa
    browser->>server: 
    activate server
    server-->>browser:
    server-->>browser:
    deactivate server

    browser->>server:
    activate server
    server-->>browser:
    deactivate server

    browser->>server:
    activate server
    server-->>browser:
    deactivate server

    browser->>server:
    activate server
    server-->>browser:
    deactivate server

    Note right of browser: The browser starts executing the JavaScript code that fetches the JSON from the server

    browser->>server:
    activate server
    server-->>browser:
    deactivate server

    Note right of browser: The browser executes the callback function that renders the notes