sequenceDiagram
    participant browser
    participant server

    browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note_spa
    browser->>server: Payload: {content: "Hola", date: "2024-03-24T14:59:24.598Z"}
    browser->>server: Headers: {Content-Type: application/json}
    activate server
    server-->>browser: Status Code: 201 (created)
    server-->>browser: {"message":"note created"}
    deactivate server

    Note right of browser: The browser starts executing the JavaScript code